### ISSUE TITLE
ImportError: No module named '_C'

### ISSUE THREAD

**Issue by ryankimky** [loolzaaa/faster-rcnn-pytorch#2]
this is my error below,

Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from script.train import train
  File "/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/script/train.py", line 12, in <module>
    from lib.model.vgg16 import VGG16
  File "/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/model/vgg16.py", line 4, in <module>
    from lib.model.faster_rcnn import FasterRCNN
  File "/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/model/faster_rcnn.py", line 6, in <module>
    from lib.model.rpn.rpn import _RPN
  File "/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/model/rpn/rpn.py", line 5, in <module>
    from lib.model.rpn.proposal_layer import _ProposalLayer
  File "/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/model/rpn/proposal_layer.py", line 7, in <module>
    from _C import nms
ImportError: No module named '_C'

**Comment by ryankimky** [comment]
i followed this compile guide that you mention.

Compile all python extensions (NMS, ROI Pooling) for CPU and CUDA with next commands:
cd lib
python setup.py develop

**Comment by loolzaaa** [comment]
If you compile process finished **without errors**, you must find this module in ./lib folder.
Name of the module: `_C.........pyd`.

Is there it?

**Comment by loolzaaa** [comment]
For windows, look like this:

![image](https://user-images.githubusercontent.com/25587684/79867050-263e4f80-83f7-11ea-9e36-fe42d7ff0eb5.png)

**Comment by ryankimky** [comment]
i work on , Linux Ubuntu 16.04.
now, i try to install and upgrade python3.5-dev.
but ,, still,,, error comes up. 

Now, I know that an error occurred during setup.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

It is being solved through stackoverflow.
but, i am not sure...

**Comment by loolzaaa** [comment]
Usually, **exact** error message you can find above text `failed with exit status 1`.

**Comment by ryankimky** [comment]
run.py script working on pytorch 1.3.0?

**Comment by loolzaaa** [comment]
**Should work**, but my version is 1.4.0.

You find exact error messages from compiler?

**Comment by ryankimky** [comment]
still not solve it..

**Comment by loolzaaa** [comment]
Find in text of console some string where there is a "error" keyword.

**Comment by kyungyulkim** [comment]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/include -I/usr/local/lib/python3.5/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.5/dist-packages/torch/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -c /storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/csrc/cpu/nms.cpp -o build/temp.linux-x86_64-3.5/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/csrc/cpu/nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

**Comment by loolzaaa** [comment]
Is there something else? Here, there is no errors...

**Comment by ryankimky** [comment]
this is log, when i run setup.py script
**Log:**
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/include -I/usr/local/lib/python3.5/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.5/dist-packages/torch/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -c /storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/csrc/cpu/nms.cpp -o build/temp.linux-x86_64-3.5/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/csrc/cpu/nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

**After then:**
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by loolzaaa** [comment]
May be you need to install additional dependencies like python-dev or something else?
Try this at start for python 3.x:
`  $ sudo apt-get install python3-dev`

**Comment by ryankimky** [comment]
can you solve this error below?
this is exact error message. 

**Error**
/storage/storage/personal/KY/jupyter_lab_2/faster-rcnn-pytorch/lib/csrc/cpu/roi_pool.cpp:49:48: error: ‘FLT_MAX’ was not declared in this scope
                     T maxval = is_empty ? 0 : -FLT_MAX;
                                                ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by loolzaaa** [comment]
Try to add in `lib/csrc/cpu/roi_pool.cpp` and `lib/csrc/cuda/roi_pool_kernel.cu` this:
```
#include <math.h>
#include <float.h>
```

**Comment by ryankimky** [comment]
I'll apply to add right away
#include <math.h>
#include <float.h>

**Comment by ryankimky** [comment]
setup was successful. 😄 
Thank you so much for the quick reply and help.
