### ISSUE TITLE
AssertionError: Path to data does not exist: VOCdevkit/VOC2007

### ISSUE THREAD

**Issue by ryankimky** [loolzaaa/faster-rcnn-pytorch#3]
![image](https://user-images.githubusercontent.com/48115105/79874846-ce6a0d80-8423-11ea-89d9-a88e23f70413.png)

What is the problem? 😭

**Comment by loolzaaa** [comment]
~~Do you download Pascal VOC dataset? Create symlinks to devkit?~~

I see, place VOCdevkit folder to **ROOT** of the library, not in the data folder.

**Comment by ryankimky** [comment]
Yes, i downloaded Pascal VOC 2007 dataset and create symlinks as follow 'https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models'

**Comment by loolzaaa** [comment]
Just create symlink in library root folder.

Well, i think, i must to fix it or write new manual, not link to old version... 😞

**Comment by loolzaaa** [comment]
I make path to data of the datasets relative `./data`, not library root in https://github.com/loolzaaa/faster-rcnn-pytorch/commit/655ef14b8b4877c0b6bf13c9a9aa5c284cd3c26c, so keep it in mind if you pull changes.

Also, you can specify your own name of the symlink and it in additional parameter at startup. Check [here](https://github.com/loolzaaa/faster-rcnn-pytorch#data-preparation).
